apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  platforms: ["linux/amd64", "linux/arm64"]
  artifacts:
    - image: apigw
      context: src/apigw
      docker:
        buildArgs:
          SKAFFOLD_GO_GCFLAGS: "all=-N -l"
          TARGETOS: linux
          TARGETARCH: amd64
  tagPolicy:
    gitCommit: {}
  local:
    useDockerCLI: true
    useBuildkit: true
manifests:
  kustomize:
    paths:
      - kubernetes-manifests
deploy:
  kubectl: {}
# apiVersion: skaffold/v3
# kind: Config
# metadata:
#   name: loadgenerator
# requires:
#   - configs:
#       - app
# build:
#   artifacts:
#     - image: loadgenerator
#       context: src/loadgenerator
# manifests:
#   rawYaml:
#     - ./kubernetes-manifests/loadgenerator.yaml
# deploy:
#   kubectl: {}
