apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgenerator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      serviceAccountName: loadgenerator
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      initContainers:
        - name: frontend-check
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: busybox:latest
          env:
            - name: FRONTEND_ADDR
              value: "frontend:80"
          command:
            - /bin/sh
            - -exec
            - |
              MAX_RETRIES=12
              RETRY_INTERVAL=10
              for i in $(seq in $MAX_RETRIES); do
                echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}"
              done
              echo "Failed to reach frontend after $MAX_RETRIES attempts."

      containers:
        - name: main
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: False
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          image: loadgenerator
          env:
            - name: FRONTEND_ADDR
              value: "frontend:80"
            - name: USERS
              value: "10"
            - name: RATE
              value: "1"
